### ISSUE TITLE
Conda installation does not work.

### ISSUE THREAD

**Issue by abhiksingla** [Weixin-Liang/LLM-scientific-feedback#1]
Getting the following error.
```
Solving environment: failed

ResolvePackageNotFound: 
  - libffi==3.4.2=h7f98852_5
  - python==3.7.12=hf930737_100_cpython
  - libstdcxx-ng==12.2.0=h46fd767_19
  - libgcc-ng==12.2.0=h65d4601_19
  - libsqlite==3.40.0=h753d276_0
  - _openmp_mutex==4.5=2_gnu
  - ca-certificates==2022.12.7=ha878542_0
  - readline==8.2=h8228510_1
  - ncurses==6.3=h27087fc_1
  - xz==5.2.6=h166bdaf_0
  - libzlib==1.2.13=h166bdaf_4
  - openssl==3.1.0=h0b41bf4_0
  - tk==8.6.12=h27826a3_0
  - libnsl==2.0.0=h7f98852_0
  - _libgcc_mutex==0.1=conda_forge
  - libgomp==12.2.0=h65d4601_19
  - sqlite==3.40.0=h4ff8645_0
  - ld_impl_linux-64==2.40=h41732ed_0
```
Even after removing =h*** suffix from the packages, some of the packages are not found.

**Comment by hiyin** [comment]
I am a user who was able to implement this successfully. You can't actually install this in Mac (which I believe you did). You need somewhat Linux machine like CentOS or other distributions to be able to make this work.

**Comment by Faultiness** [comment]
@hiyin Thanks for your suggestion. I finally managed to run the whole pipeline on Ubuntu 22.04 in x64 Win10 VMware.

Any suggestions to run the entire pipeline natively on Mac or Windows? Just for reference:
- Native M1 version anaconda on Mac, same error
- Ubuntu 22.04 arm64 in Parallels Desktop, same error
- Ubuntu 22.04 x86_64 with Rosetta in Parallels Desktop, rosetta error, and failed to install anaconda
- Native Windows version anaconda on x64 Win10, same error

**Comment by Boltzmachine** [comment]
docker on Mac also failed

**Comment by yuhui-zh15** [comment]
Thanks for your interest in our system. Unfortunately ScienceBeam only supports Linux. Let us know if you find a way to install ScienceBeam on other systems.

**Comment by yuhui-zh15** [comment]
We now added a new system that supports texts as input:

Usage:
```bash
python main_from_text.py  # If you are using non-linux operating systems or want to generate feedback from the parsed paper in text format
```
