### ISSUE TITLE
Failed to parse XML... Error: not well-formed (invalid token): line 1, column 0

### ISSUE THREAD

**Issue by liuliAI** [Weixin-Liang/LLM-scientific-feedback#10]
Failed to parse XML... Error: not well-formed (invalid token): line 1, column 0
Running on local URL:  http://127.0.0.1:7860
Parsing PDF...
Parsing XML...

**Comment by Zhong-Zhang** [comment]
Try this: https://github.com/Weixin-Liang/LLM-scientific-feedback/issues/6#issuecomment-1751886948

**Comment by liuliAI** [comment]
> Try this: [#6 (comment)](https://github.com/Weixin-Liang/LLM-scientific-feedback/issues/6#issuecomment-1751886948)

I tried, no changes

**Comment by Zhong-Zhang** [comment]
Try to alter the port of the parser server, 8080 might be occupied by other apps:

`python -m sciencebeam_parser.service.server --port=7080`

and the main.py:

`convert_url = "http://localhost:7080/api/convert"`

**Comment by alexmaehon** [comment]
> Try to alter the port of the parser server, 8080 might be occupied by other apps:
> 
> `python -m sciencebeam_parser.service.server --port=7080`
> 
> and the main.py:
> 
> `convert_url = "http://localhost:7080/api/convert"`

changed port still not working

**Comment by yuhui-zh15** [comment]
Thanks for your interest in our system. It seems this error happens when running on non-linux system. Unfortunately ScienceBeam only supports x86 Linux. Let us know if you find a way to install ScienceBeam on other systems.

**Comment by yuhui-zh15** [comment]
We now added a new system that supports texts as input:

Usage:
```bash
python main_from_text.py  # If you are using non-linux operating systems or want to generate feedback from the parsed paper in text format
```
