### ISSUE TITLE
Considering the fact that more and more people write their paper with latex,I think you should supprt the .tex file

### ISSUE THREAD

**Issue by XJLeoYu** [Weixin-Liang/LLM-scientific-feedback#14]

**Comment by XJLeoYu** [comment]
Maybe other language model should also be supported like PaLM 2 (Bison-001) Claude Cohere Falcon and so on

**Comment by yuhui-zh15** [comment]
Hi, thanks for your suggestion! We currently don't have plans for further support, but we welcome pull requests if you are interested.
