### ISSUE TITLE
Failed to parse XML

### ISSUE THREAD

**Issue by KyleWang1026** [Weixin-Liang/LLM-scientific-feedback#16]
我在Intel芯片的Mac上用虚拟机安装了Ubuntu系统，前面都没问题，最后一步submit PDF文件后，在解析XML文件时报错“Failed to parse XML... Error: syntax error: line 1, column 0”：
<img width="1004" alt="截屏2023-10-09 23 15 27" src="https://github.com/Weixin-Liang/LLM-scientific-feedback/assets/116907127/d564f937-f99f-4825-8843-d5c79d7d7c06">

下图是sciencebeam_parser.service.server后台运行报错：
<img width="1370" alt="截屏2023-10-09 23 17 08" src="https://github.com/Weixin-Liang/LLM-scientific-feedback/assets/116907127/de110afa-0dad-4f55-8d0c-09dca8567d93">

<img width="1371" alt="截屏2023-10-09 23 17 21" src="https://github.com/Weixin-Liang/LLM-scientific-feedback/assets/116907127/500e1f3b-cf52-4c80-84f4-d8239906440f">

费很大力气才把环境配置好，最后一步不知道为什么显示No such file or directory.

**Comment by chencn2020** [comment]
蹲

**Comment by alexmaehon** [comment]
一样，Failed to parse XML... Error: syntax error: line 1, column 0

**Comment by kyleearth** [comment]
same issue

**Comment by sunchongwei** [comment]
这个不是自己环境的问题，是软件的问题，软件在转换xml的过程中出错了，我现在的方法是本地转成xml直接上传解析，稍微改动一下代码，就能得到评审结果

**Comment by lxd4321** [comment]
@sunchongwei 本地用什么工具转呢

**Comment by yuhui-zh15** [comment]
Thanks for your interest in our system. Unfortunately ScienceBeam only supports x86 Linux. Let us know if you find a way to install ScienceBeam on other systems.

**Comment by yuhui-zh15** [comment]
We now added a new system that supports texts as input:

Usage:
```bash
python main_from_text.py  # If you are using non-linux operating systems or want to generate feedback from the parsed paper in text format
```

**Comment by KyleWang1026** [comment]
Finally solved this problem! 
ScienceBeam contains a file "wapitil_install.py", and error occurs when running the code in lines 38-41: 
"subprocess.check_output(
        'make',
        cwd=wapiti_source_directory
)"
Reason:  Can't find the 'make' command.
Solution:  sudo apt  install make

**Comment by KyleWang1026** [comment]
Finally solved this problem! 
ScienceBeam contains a file "wapitil_install.py", and error occurs when running the code in lines 38-41: 
"subprocess.check_output(
        'make',
        cwd=wapiti_source_directory
)"
Reason:  Can't find the 'make' command.
Solution:  sudo apt  install make

**Comment by KyleWang1026** [comment]
> 这个不是自己环境的问题，是软件的问题，软件在转换xml的过程中出错了，我现在的方法是本地转成xml直接上传解析，稍微改动一下代码，就能得到评审结果

实际上是的，没装‘make’命令，安装后重新运行就解决了。
