### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by jianke22** [Weixin-Liang/LLM-scientific-feedback#19]
I got the following error message:
Failed to generate review... Error: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.

![image](https://github.com/Weixin-Liang/LLM-scientific-feedback/assets/13138403/b3be095d-24a5-453f-a1ef-2014226be8bb)

Anyone knows what is the solution?

**Comment by yuhui-zh15** [comment]
Please add OpenAI api key by:
`cat YOUR_OPENAI_API_KEY > key.txt`

 Replace YOUR_OPENAI_API_KEY with your OpenAI API key starting with "sk-"
