### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by abhiksingla** [Weixin-Liang/LLM-scientific-feedback#2]
requirements.txt is missing

**Comment by hiyin** [comment]
The <requirements.txt> should contain:
gradio
pikepdf
openai
tiktoken

these 4 packages. 

You can create your own requirements.txt or just pip install them one by one. Indeed the requirements.txt is missing from the repository but we can somehow guess from the main.py what is required.

**Comment by yuhui-zh15** [comment]
Thanks @hiyin! We added it now
