### ISSUE TITLE
conda_environment.yml在Ubantu中安装出错

### ISSUE THREAD

**Issue by XinyeYang** [Weixin-Liang/LLM-scientific-feedback#7]
在Mac M1和Ubantu中安装都遇到了错误
<img width="1512" alt="PDFParse" src="https://github.com/Weixin-Liang/LLM-scientific-feedback/assets/61686580/a8f2578a-c4d0-40e7-8184-565a50598ebb">

**Comment by XinyeYang** [comment]
你好，其他issue中提到的开放接口已经打不开了

**Comment by Zhong-Zhang** [comment]
MacBook Intel Chip also failed, I believe the project cannot run on Mac (M1 and Intel). I finally have it worked on Ubuntu 22.04. Try to update the conda and source.

**Comment by XinyeYang** [comment]
I just installed the latest version of MiniConda in Ubuntu22.04.

**Comment by Zhong-Zhang** [comment]
> I installed the latest version of miniconda in Ubuntu22.04 and it still fails.


I didn't use miniconda, here is my conda info:

<img width="591" alt="image" src="https://github.com/Weixin-Liang/LLM-scientific-feedback/assets/42954562/b0964351-71a0-465e-9d2b-f88dd6235ba9">

**Comment by XinyeYang** [comment]
I tried anaconda3 in Ubuntu22.04 and got the same error. It may not work on arm systems. 😔

**Comment by yuhui-zh15** [comment]
Thanks for your interest in our system. Unfortunately ScienceBeam only supports x86 Linux. Let us know if you find a way to install ScienceBeam on other systems.

**Comment by yuhui-zh15** [comment]
We now added a new system that supports texts as input:

Usage:
```bash
python main_from_text.py  # If you are using non-linux operating systems or want to generate feedback from the parsed paper in text format
```
