### ISSUE TITLE
error in step1： create a PDF parsing server and run in the background ？

### ISSUE THREAD

**Issue by zinojeng** [Weixin-Liang/LLM-scientific-feedback#8]
How to install sciencebeam_parser, how to solve it

error message: /opt/homebrew/opt/python@3.11/bin/python3.11: Error while finding module specification for 'sciencebeam_parser.service.server' (ModuleNotFoundError: No module named 'sciencebeam_parser')

After pip3 install sciencebeam_parser：
 Error while finding module specification for 'sciencebeam_parser.service.server' (ModuleNotFoundError: No module named 'sciencebeam_parser')

**Comment by yuhui-zh15** [comment]
Thanks for your interest in our system. Unfortunately ScienceBeam has very strict system requirement. Please follow the correct ScienceBeam installation guide instead of using pip.
